---
  - hosts: all
    become: yes
    become_method: sudo
    tasks:
      - name: 1. Update OS
        command: apt update

      - name: 2. Install aptitude using apt
        apt:
          name: aptitude
          state: latest
          force_apt_get: yes

      - name: 3. Install common required system packages
        apt:
          name:
            - "gpg"
            - "jq"
            - "unzip"
            - "wget"
            - "git"
            - "python3-pip"
            - "python3-setuptools"
          state: latest
          force_apt_get: yes

      - name: 4. Add the intermediate certificate to certificate bundle
        command: update-ca-certificates

      - name: 5. Install software properties common
        apt:
          name: software-properties-common
          state: latest
          force_apt_get: yes
