---
  - hosts: ap-s1
    become: yes
    become_method: sudo
    vars_files:
      - host_vars/ap-s1.yml
    vars:
      ansible_ssh_private_key_file: "{{ private_key }}"
    tasks:
      - name: 0. Get root user
        shell: |
          echo "root:12345678xX" | sudo chpasswd

      - name: 1. Update OS
        command: apt update

      - name: 2. Install aptitude using apt
        apt:
          name: aptitude
          state: latest
          force_apt_get: yes

      - name: 3. Install common required system packages
        apt:
          name: "{{ common_required_packages }}"
          state: latest
          force_apt_get: yes

      - name: 4. Add the intermediate certificate to certificate bundle
        command: update-ca-certificates

      # - name: 5. Install ca cerfiticates
      #   apt:
      #     name: ca-cerfiticates
      #     state: latest
      #     update_cache: yes

      - name: 5. Install software properties common
        apt:
          name: software-properties-common
          state: latest
          force_apt_get: yes